services:
  web:
    build: .
    ports:
      - "3000:80"
    env_file:
      - .env
    volumes:
      - ./storage:/rails/storage
      - ./db:/rails/db
    restart: always
    deploy:
      resources:
        limits:
          memory: 1024M # The "Hard" ceiling
        reservations:
          memory: 512M # The "Soft" guarantee
