services:
  web:
    build: .
    ports:
      - "3000:80"
    env_file:
      - .env
    volumes:
      # Change these two lines to use the named volumes
      - rails_storage:/rails/storage
      - rails_db:/rails/db
    restart: always
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M

volumes:
  rails_storage:
  rails_db:
